---
driver:
  name: dokken
  
provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_ansible_repo: true
  ansible_verbose: true
  require_chef_for_busser: false
  playbook: site.yml

transport:
  max_ssh_sessions: 6

verifier:
  name: inspec

platforms:
  - name: windows
    driver_config:
      image: mcr.microsoft.com/windows
      platform: windows

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default