---
driver:
  name: docker
  
provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_ansible_repo: true
  ansible_verbose: true
  require_chef_for_busser: false
  playbook: site.yml

transport:
  max_ssh_sessions: 6

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    lifecycle:
      pre_verify:
        - inspec compliance login https://10.11.1.147 --user admin --insecure --token "w9jKIRHIm9vMBW_3s95spyX9O2M="
    verifier:
      inspec_tests:
        - name: cis-centos7-level1-server
          compliance: admin/cis-centos7-level1-server